name: Build Docker Image Sample

on: push

env: # global環境変数を設定
  DOCKER_IMAGE_NAME: crdemo
  CR_HOST: ${{ secrets.CR_HOST }}
  CR_USERNAME: ${{ github.repository_owner }}
  CR_PASSWORD: ${{ secrets.CR_PAT }}

jobs:
  push_docker_image:
    if: contains( github.ref, 'release') #releaseブランチにpushされたときに実行する
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME -f ./Dockerfile . 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CR_HOST }}
          username: ${{ env.CR_USERNAME }}
          password: ${{ env.CR_PASSWORD }}
      - name: Push docker image to GitHub Container Registry
        run: | 
            IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/heads/release/v##g")
            IMAGE_TAG_WITH_CR=${CR_HOST}/${CR_USERNAME,,}/${DOCKER_IMAGE_NAME}:$IMAGE_TAG
            docker tag $DOCKER_IMAGE_NAME $IMAGE_TAG_WITH_CR
            docker push $IMAGE_TAG_WITH_CR
