name: Create Git Tag

on:
  pull_request:
    branches:
      - main
    types: [closed]
    
jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: echo github merged branch name
        run: |
          echo "base_ref: ${{ github.base_ref }}"
      - uses: actions/checkout@v2
      - run: |
          echo "v1-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
