on: workflow_dispatch

name: Workflow dispatch events

jobs:
  dispatch:
    name: Workflow dispatch events
    runs-on: ubuntu-latest

    steps:
    - name: ffmpeg command in docker container
      run: |
        docker run -v $(pwd):$(pwd) -w $(pwd) -t --rm jrottenberg/ffmpeg:3.2-alpine -f lavfi -i smptehdbars=1920x1080:d=10 -f lavfi -i sine=frequency=1000:d=10 output.mp4
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: output.mp4