name: Create Git Tag

on:
  pull_request:
    branches:
      - main
    types: [closed]
    
jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains( github.head_ref, 'release')
    steps:
      - name: echo github merged branch name
        run: |
          echo "base_ref: ${{ github.base_ref }}"
          echo "head_ref: ${{ github.head_ref }}"
      - uses: actions/checkout@v2
      - run: |
          GIT_TAG=$(echo ${{ github.head_ref }} | sed -e "s#release/v##g")
          git tag $GIT_TAG
          git push origin $GIT_TAG
